title: OpenZipkin

description: >
  Zipkin is a distributed tracing system. It helps gather timing data needed to
  troubleshoot latency problems in microservice architectures.

twitter_username: zipkinproject
github_username:  openzipkin

defaults:
  -
    values:
      layout: page
